Repository fylein/fyle-ms-business-central-api, pull requests merged in 2024-10, with the labels that each got.

#163 modify the update condition
  apps/fyle/tasks.py
  tests/test_fyle/test_tasks.py
Labels: size/S

#168 chore: bump-mappings-version-34.8
  requirements.txt
Labels: size/XS

#167 feat: Add extensive logger and limits
  apps/business_central/utils.py
  ms_business_central_api/settings.py
  requirements.txt
  tests/test_business_central/test_utils.py
  tests/test_mappings/test_imports/test_modules/test_base.py
  tests/test_mappings/test_imports/test_modules/test_categories.py
  tests/test_mappings/test_imports/test_modules/test_cost_centers.py
  tests/test_mappings/test_imports/test_modules/test_expense_custom_fields.py
  tests/test_mappings/test_imports/test_modules/test_merchants.py
Labels: deploy, size/M
