Repository fylein/fyle-ms-business-central-api, pull requests merged in 2024-11, with the labels that each got.

#171 fix: remove sentry transaction sampling
  ms_business_central_api/sentry.py
Labels: size/XS

#170 Fix: All the bug fixes listed
  apps/accounting_exports/models.py
  apps/business_central/actions.py
  apps/business_central/exports/base_model.py
  apps/mappings/tasks.py
  apps/workspaces/tasks.py
  tests/test_workspaces/test_tasks.py
Labels: deploy, size/S

#172 feat: handle posted at
  apps/fyle/models.py
Labels: size/XS

#175 Feat: Adding new Journal Entry changes
  apps/business_central/exports/journal_entry/models.py
  apps/business_central/exports/journal_entry/tasks.py
Labels: size/M

#174 Feat: Support for dimension during export Journal Entry and purchase Invoice
  apps/business_central/exports/base_model.py
  apps/business_central/exports/journal_entry/models.py
  apps/business_central/exports/journal_entry/tasks.py
  apps/business_central/exports/purchase_invoice/models.py
  apps/business_central/exports/purchase_invoice/tasks.py
  apps/business_central/migrations/0002_journalentrylineitems_dimensions_and_more.py
  apps/business_central/migrations/0003_journalentrylineitems_dimension_error_log_and_more.py
  apps/business_central/migrations/0004_journalentrylineitems_dimension_success_log_and_more.py
  apps/business_central/utils.py
  apps/mappings/imports/modules/base.py
Labels: deploy, size/L

#176 fix: expense migration
  apps/fyle/migrations/0004_expense_is_posted_at_null.py
  apps/fyle/models.py
  requirements.txt
  tests/test_business_central/fixtures.py
  tests/test_fyle/fixtures.py
  tests/test_fyle/test_tasks.py
Labels: size/S
