Repository fylein/fyle-ms-business-central-api, pull requests merged in 2024-12, with the labels that each got.

#177 Feat: Add chart of accounts type when importing accounts to category in Fyle
  apps/business_central/utils.py
  apps/mappings/imports/modules/base.py
  apps/mappings/imports/modules/categories.py
  apps/mappings/imports/queues.py
  apps/mappings/imports/tasks.py
  apps/workspaces/migrations/0004_importsetting_charts_of_accounts.py
  apps/workspaces/models.py
  apps/workspaces/serializers.py
  requirements.txt
  tests/test_fyle/fixtures.py
  tests/test_mappings/test_imports/test_modules/test_base.py
  tests/test_mappings/test_imports/test_modules/test_categories.py
  tests/test_workspaces/test_view.py
Labels: size/M

#178 fix: bump fyle accounting mappings version
  requirements.txt
Labels: size/XS

#180 Fix: Adding default ccc bank account
  apps/business_central/exports/journal_entry/models.py
  apps/business_central/serializers.py
  apps/fyle/serializers.py
  apps/workspaces/migrations/0005_exportsetting_default_ccc_bank_account_id_and_more.py
  apps/workspaces/migrations/0006_rename_default_ccc_bank_account_id_exportsetting_default_ccc_bank_account_id_and_more.py
  apps/workspaces/models.py
Labels: deploy, size/M

#179 Fix: Removing condition for bank account in sync data
  apps/business_central/exports/journal_entry/models.py
  apps/business_central/exports/journal_entry/tasks.py
  apps/business_central/serializers.py
  apps/business_central/utils.py
  apps/fyle/serializers.py
  apps/workspaces/migrations/0005_exportsetting_default_ccc_bank_account_id_and_more.py
  apps/workspaces/migrations/0006_rename_default_ccc_bank_account_id_exportsetting_default_ccc_bank_account_id_and_more.py
  apps/workspaces/models.py
  apps/workspaces/serializers.py
Labels: deploy, size/M

#181 fix: delete `expense_attributes_deletion_cache` in workspace reset
  scripts/sql/reset_db.sql
Labels: size/XS

#183 fix: Added version to openpyxl
  requirements.txt
Labels: size/XS

#182 chore: bump accounting mapping version
  requirements.txt
  tests/test_business_central/conftest.py
  tests/test_workspaces/test_tasks.py
Labels: size/S
